<a href="https://colab.research.google.com/github/icaroperetti/artificial-intelligence/blob/main/redes-neurais/rna_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Connect to google drive
from google.colab import drive
drive.mount('/content/drive',force_remount=False)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [1]:
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense, Dropout
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plth
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import Normalizer
from sklearn import metrics

#Path of the file in my drive
# https://www.kaggle.com/datasets/somesh24/spambase?select=spambase_csv.csv  - E-mail spam

file_path = 'https://raw.githubusercontent.com/icaroperetti/spam-kaggle-csv/main/spambase_csv.csv'


# load the dataset
dataset = loadtxt(file_path,delimiter=",")

X = dataset[:,0:57] # Dados
y = dataset[:,57] # Classe 0 - Não é spam  1 - É spam

print('Before',X)

X = Normalizer().fit(X).transform(X)

print('After',X)

print(X.shape,y.shape)

# print(X,'\n\n',y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=80, shuffle=True)


model = Sequential()
model.add(Dense(100, input_dim=X.shape[1], activation='relu'))
model.add(Dropout(0.2)) # Ainda não sei pra que serve
model.add(Dense(33, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(11, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(1, activation='sigmoid'))

# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])


# fit the keras model on the dataset
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=200, batch_size=100)


loss, accuracy = model.evaluate(X, y)
print('Accuracy: %.2f' % (accuracy*100))
print('Loss: %.2f' % (loss*100))


Before [[0.000e+00 6.400e-01 6.400e-01 ... 3.756e+00 6.100e+01 2.780e+02]
 [2.100e-01 2.800e-01 5.000e-01 ... 5.114e+00 1.010e+02 1.028e+03]
 [6.000e-02 0.000e+00 7.100e-01 ... 9.821e+00 4.850e+02 2.259e+03]
 ...
 [3.000e-01 0.000e+00 3.000e-01 ... 1.404e+00 6.000e+00 1.180e+02]
 [9.600e-01 0.000e+00 0.000e+00 ... 1.147e+00 5.000e+00 7.800e+01]
 [0.000e+00 0.000e+00 6.500e-01 ... 1.250e+00 5.000e+00 4.000e+01]]
After [[0.00000000e+00 2.24834975e-03 2.24834975e-03 ... 1.31950026e-02
  2.14295835e-01 9.76626921e-01]
 [2.03297105e-04 2.71062806e-04 4.84040726e-04 ... 4.95076854e-03
  9.77762266e-02 9.95187732e-01]
 [2.59683978e-05 0.00000000e+00 3.07292708e-04 ... 4.25059392e-03
  2.09911216e-01 9.77710178e-01]
 ...
 [2.53812946e-03 0.00000000e+00 2.53812946e-03 ... 1.18784459e-02
  5.07625892e-02 9.98330921e-01]
 [1.22759766e-02 0.00000000e+00 0.00000000e+00 ... 1.46672345e-02
  6.39373781e-02 9.97423098e-01]
 [0.00000000e+00 0.00000000e+00 1.59858723e-02 ... 3.07420620e-02
  1.22968248e